project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd # referemce qmd
        text: Home # qmd name that shows on website
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Bio
      - href: relevant_course.qmd
        text: Relevant Coursework
  page-footer:
    right: "&copy; 2024, Mana Nakano"
      

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

execute: 
  freeze: auto # only renders the files that were changed
  
  
  
  