project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd # referemce qmd
        text: Home # qmd name that shows on website
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: Bio
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute: 
  freeze: auto # only renders the files that were changed
  
  
  
  